#################################################################
#via this config you can enable "nether"-Features. This is for  #
#people who like to disable the nether!                         #
#################################################################
PrivateJoinMessage: Hi there! Have a nice stay! online%
###
netherrack: true
netherbrick: true
glowstone: true
soulsand: true
blazerod: true
netherstar: true
netherwartseed: true